### ISSUE TITLE
Does not support encoding

### ISSUE THREAD

**Issue by z4gunn** [ChrisPulman/SerialPortRx#1]
This is a great Rx serial library, but the default encoding is set to ASCII.  In order to read raw (non-encoded) bytes from the device the encoding needs to be set to extended ASCII to avoid data corruption.  I have made the necessary code change and would like to push if you would like.

**Comment by ChrisPulman** [comment]
I have exposed the Encoding property to allow you to set the encoding that you require (Encoding.GetEncoding(1252) I believe).
If you are satisfied with this addition please close the issue.
If this is not enough please submit a pull request with your suggestions.
Thanks

**Comment by z4gunn** [comment]
Thanks that should work great!
