### ISSUE TITLE
Does error handling work? Or am I missing how it is supposed to work

### ISSUE THREAD

**Issue by professordave** [ChrisPulman/SerialPortRx#5]
What is the intent with error handling? And the infinite retry logic. Am I missing something with the retry logic? If the port is bad retrying forever is not the correct thing to do. 

The task-> run is wrapped by a calling function open(), which means the caller cannot await any errors? Or can it? I am somewhat new to the latest c# features.

Exceptions thrown from the underlying open are not trapped for at all, in contrast to the write which does trap for errors.

However, even the errors from write are trapped and thrown to the "connect" But the connect is done with a task => run so that those errors are lost, I think. 

I am wondering if it is as simple as for real physical ports, open and write never fail. And therefore there was no need for error handling as the library writer here only used with real physical com ports??

I am using this with USB Virtual com ports and the open and the writes can fail

**Comment by ChrisPulman** [comment]
Try the new example code and see if this gives you what you need.

**Comment by ChrisPulman** [comment]
I will close this as no further feedback has been made for 3 months
